apiVersion: apps/v1
kind: Deployment
metadata:
  name: other-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: other-app
  template:
    metadata:
      labels:
        app: other-app
    spec:
      containers:
        - name: springboot
          image: rahulwagh17/rest-webservice:rest-webservice

          resources:
            requests:
              memory: "128Mi"
              cpu: "512m"
            limits:
              memory: "128Mi"
              cpu: "512m"

          ports:
            - containerPort: 9090
          env:
            - name: PORT
              value: "9090"
---
apiVersion: v1
kind: Service
metadata:
  name: other-app
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: other-app